# Site settings
title: 星のない空
email: aquarhead@ela.build
description: >
  終わらない夜に願いはひとつ<br />
  ｢星のない空に輝く光を｣
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.aquarhead.me" # the base hostname & protocol for your site
port: 4001
twitter_username: aquarhead
github_username:  aquarhead
permalink: /:year/:month/:title

# Build settings
markdown: kramdown
kramdown:
  input: GFM
